[build]
  command: ./stackbit-build.sh
  commandOrigin: config
  environment:
    - STACKBIT_API_KEY
    - HUGO_VERSION
  publish: /opt/build/repo/public

  [build.environment]
  HUGO_VERSION = "0.47"
